/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "addresstype",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			columnName: "addTypeId",
			isInteger: true,
			required: true
		},
		addtType: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		display: {
			type: "string",
			columnType: "varchar",
			maxLength: 255
		},
		withcheckbox: {
			type: "string",
			columnType: "enum",
			isIn: ["1", "0"],
			defaultsTo: "0"
		},
		createdon: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	}
};
