/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		analysis_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		filename: {
			type: "string",
			columnType: "varchar",
			maxLength: 300,
			required: true
		},
		created_date: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	},
	tableName: "analysis_file"
};
