/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			columnName: "idanalysis_finance",
			isInteger: true,
			required: true
		},
		type: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			defaultsTo: "itr,finance"
		},
		document_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		loan_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		business_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		userid: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		extracted_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 105
		},
		excel_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 105
		},
		created_time: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	},
	tableName: "analysis_finance"
};
