/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		doc_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		userid: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		doc_name: {
			type: "string",
			columnType: "text",
			required: true
		},
		loan_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		created_time_request: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		},
		type_read: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		type: {
			type: "string",
			columnType: "text",
			required: true
		},
		first_conversion: {
			type: "string",
			columnType: "varchar",
			maxLength: 100
		},
		compained_file: {
			type: "string",
			columnType: "text"
		},
		output_file: {
			type: "string",
			columnType: "text"
		},
		created_date: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		total_errors: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		toal_rows: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		date_error: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		total_dates: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		notification: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		bank_summary: {
			type: "string",
			columnType: "varchar",
			maxLength: 100
		},
		account_credit: {
			type: "string",
			columnType: "varchar",
			maxLength: 145
		},
		account_debit: {
			type: "string",
			columnType: "varchar",
			maxLength: 145
		},
		analysis_credit: {
			type: "string",
			columnType: "varchar",
			maxLength: 145
		},
		analysis_debit: {
			type: "string",
			columnType: "varchar",
			maxLength: 145
		},
		excel_file: {
			type: "string",
			columnType: "varchar",
			maxLength: 165
		},
		status_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			defaultsTo: "0"
		},
		daily_balance: {
			type: "string",
			columnType: "text"
		},
		analysis_abstract_credit: {
			type: "string",
			columnType: "text"
		},
		analysis_abstract_debit: {
			type: "string",
			columnType: "text"
		},
		more_analysis_file: {
			type: "string",
			columnType: "text"
		},
		bank_snapshot_file: {
			type: "string",
			columnType: "text"
		},
		updated_timestap: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		noPage: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		reference_tab: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			defaultsTo: "loan_document"
		},
		extract_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		}
	},
	tableName: "analysis_data"
};
