/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		assettype_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		value: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		text: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		}
	},
	tableName: "asset_type_mapping_cersai"
};
