/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			autoIncrement: true,
			columnName: "assignment_log_id",
			isInteger: true
		},
		action_event: {
			type: "string",
			columnType: "text",
			required: true
		},
		action_ref_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		notification: {
			type: "string",
			columnType: "enum",
			isIn: ["1", "0"],
			defaultsTo: "1"
		},
		event_ref_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		created_by: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		ints: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		upts: {
			type: "ref",
			columnType: "datetime"
		},
		remarks: {
			type: "string",
			columnType: "text"
		}
	},
	tableName: "assignment_log"
};
