/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		route_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		url: {
			type: "string",
			columnType: "text",
			required: true
		},
		action: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		action_result_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		action_reference: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		ip_address: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		request_time: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		user_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		}
	}
};
