/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "bank_master",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			columnName: "bankid",
			isInteger: true,
			required: true
		},
		bankname: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		isLender: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "No"
		},
		type: {
			type: "string",
			columnType: "enum",
			isIn: ["bank", "nbfc"],
			defaultsTo: "Bank"
		},
		category: {
			type: "string",
			columnType: "enum",
			isIn: ["nbfc", "regional bank", "international bank", "national private bank", "national public bank"],
			defaultsTo: "National Public Bank"
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"],
			defaultsTo: "active"
		},
		parent_bank_flag: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "Yes"
		},
		bank_acc_expression: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		yodlee_site_id: {
			type: "number",
			columnType: "bigint",
			isInteger: true,
			required: true
		},
		parent_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		white_label_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		logo_url: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		min_loan_amt: {
			type: "number",
			columnType: "bigint",
			allowNull: true
		},
		max_loan_amt: {
			type: "number",
			columnType: "bigint",
			allowNull: true
		}
	},
	customToJSON: function () {
		// Return a shallow copy of this record with the password and ssn removed.
		return _.omit(this, [
			"isLender",
			"type",
			"category",
			"status",
			"parent_bank_flag",
			"bank_acc_expression",
			"yodlee_site_id",
			"parent_id"
		]);
	}
};
