/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		type: {
			type: "string",
			columnType: "enum",
			isIn: ["auth", "data", "status"],
			required: true
		},
		url: {
			type: "string",
			columnType: "text",
			required: true
		},
		data_format: {
			type: "string",
			columnType: "longtext",
			required: true
		},
		data_format_mapping: {
			type: "string",
			columnType: "longtext",
			required: true
		},
		table_for_prepare_data: {
			type: "string",
			columnType: "longtext"
		},
		table_for_prepare_data_join: {
			type: "string",
			columnType: "longtext"
		},
		output_validation: {
			type: "string",
			columnType: "longtext",
			required: true
		},
		exec_order: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		lender_user_id: {
			type: "number",
			columnType: "bigint",
			isInteger: true,
			required: true
		},
		bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		white_label_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_product_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_sub_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_bank_staus: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_borrower_status: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		sales_required_in_city: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no", "not_applicable"],
			required: true
		},
		exclude_digital_cities: {
			type: "string",
			columnType: "longtext",
			required: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive"],
			required: true
		},
		created_date: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		updated_date: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	},
	tableName: "bank_integration"
};
