/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "banktbl",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		ref_id: {
			type: "number",
			columnType: "int",
			required: true
		},
		bank: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		ifsc: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		branch: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		contact: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		address: {
			type: "string",
			columnType: "text",
			required: true
		},
		city: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		district: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		state: {
			type: "string",
			columnType: "varchar",
			required: true
		},
		section_reference_id: {
			type: "string",
			columnType: "varchar"
		},
		email_id: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		Classification_Type: {
			type: "string",
			columnType: "varchar"
		},
		Additional_email_id: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		branch_pincode: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			defaultsTo: "NULL"
		}
	}
};
