/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_document_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		filename: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		}
	},
	tableName: "bank_analysis_category"
};
