/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 13:51:13 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "bank_products",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			columnName: "idbank_products",
			isInteger: true,
			required: true
		},
		product_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		product_pre_save_amount_needed: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"]
		},
		product_pre_save_amount_percentage: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		push_plan: {
			type: "string",
			columnType: "enum",
			isIn: ["monthly", "date_based"],
			required: true
		},
		label_value: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		label_amount: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		label_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		product_status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "not active"]
		},
		created_date: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		modifided_date: {
			type: "ref",
			columnType: "timestamp"
		},
		product_img_src: {
			type: "string",
			columnType: "text",
			required: true
		},
		product_cat_img_android: {
			type: "string",
			columnType: "text",
			required: true
		},
		product_desc: {
			type: "string",
			columnType: "text",
			required: true
		}
	}
};
