/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "business",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "businessid",
			isInteger: true
		},
		businessname: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		business_address: {
			collection: "businessaddressrd",
			via: "bid"
		},
		userid: {
			model: "usersrd"
		},
		first_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100
		},
		last_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100
		},
		business_email: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		contactno: {
			type: "string",
			columnType: "varchar",
			maxLength: 15
		},
		businesstype: {
			model: "businesstyperd"
		},
		// businessindustry: {
		//   type: 'number',
		//   columnType: 'int',
		//   isInteger: true,
		//   defaultsTo: 20
		// },
		businessindustry: {
			model: "BusinessIndustryrd"
		},
		businessstartdate: {
			type: "string",
			columnType: "varchar",
			maxLength: 30,
			required: true
		},
		businesspancardnumber: {
			type: "string",
			columnType: "varchar"
		},
		corporateid: {
			type: "string",
			columnType: "varchar",
			maxLength: 50
		},
		percentage_business_supplier: {
			type: "number",
			columnType: "float"
		},
		percentage_business: {
			type: "number",
			columnType: "float"
		},
		empcount: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		noofdirectors: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		about_business: {
			type: "string",
			columnType: "text"
		},
		current_company: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		previous_company: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"],
			defaultsTo: "active"
		},
		ints: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		white_label_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			defaultsTo: "1"
		},
		business_truecaller_info: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		google_search_data: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		gstin: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		gstin_extract: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		is_ca_business: {
			type: "number",
			columnType: "tinyint",
			isInteger: true,
			defaultsTo: 0
		},
		encrypted_data: {
			type: "string",
			columnType: "blob",
			allowNull: true
		},
		pancard_url: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		ITR_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		filling_date: {
			type: "ref",
			columnType: "datetime"
		},
		crime_check: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			defaultsTo: "No"
		},
		remarks: {
			type: "string",
			columnType: "json",
			allowNull: true
		},
		email_verification: {
			type: "string",
			columnType: "LONGTEXT",
			allowNull: true
		},
		notification_v: {
			type: "number",
			columnType: "int",
			defaultsTo: 1
		},
		notification_purpose_v: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			defaultsTo: "1"
		},
		customer_picture: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		profile_ref_no: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		profile_branch_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		existing_customer: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			defaultsTo: "No"
		},
		customer_id: {
			type: "string",
			columnType: "varchar",
			columnName: "customer_id",
			maxLength: 50,
			allowNull: true
		},
		title: {
			type: "string",
			columnType: "enum",
			isIn: ["Miss", "Mrs", "Ms", "Mr", "Mx", "Dr", "Others"],
			allowNull: true
		},
		udyam_number: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		udyam_response: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		tel_o: {
			type: "string",
			columnType: "varchar",
			maxLength: 20,
			allowNull: true
		},
		preferred_mailing_address: {
			type: "string",
			columnType: "varchar",
			maxLength: 30,
			allowNull: true
		},
		additional_info : {
			type: "string",
			columnType: "json",
			allowNull: true
		}
	}
};
