/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "channel_type",
	attributes: {
		id: {
			type: "number",
			columnType: "int",
			columnName: "channel_id",
			isInteger: true,
			required: true
		},
		channel_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		}
	}
};
