/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "city_state_master",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "city_id",
			isInteger: true,
			required: true
		},
		city: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		state: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		}
	}
};
