/**
	Generated by sails-inverse-model
	Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "doctype",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "doc_type_id",
			isInteger: true,
			required: true
		},
		doc_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 250,
			required: true
		},
		name: {
			type: "string",
			columnType: "varchar",
			maxLength: 250,
			required: true
		},
		priority: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1", "2", "100", "200", "300", "400"],
			defaultsTo: "1"
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"],
			defaultsTo: "active"
		},
		mandatory: {
			type: "string",
			columnType: "enum",
			isIn: ["1", "0"],
			required: true
		},
		loan_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 30,
			required: true
		},
		doc_detail: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		white_label_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		excel_sheet_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 199,
			required: true
		},
		order: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		document_subtype: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1", "2", "3", "4", "5"],
			defaultsTo: "0"
		},
		loan_product_document_mapping: {
			collection: "loanproductdocumentmapping",
			via: "doctype_id"
		}
	}
};
