/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "income_data",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true
		},
		business_id: {
			type: "number",
			columnType: "bigint",
			required: true
		},
		director_id: {
			type: "number",
			columnType: "int"
		},
		gross_income: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		net_monthly_income: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		isActive: {
			type: "string",
			columnType: "enum",
			isIn: ["true", "false"],
			defaultsTo: "true"
		},
		created_at: {
			type: "ref",
			columnType: "datetime",
			autoCreatedAt: true
		},
		updated_at: {
			type: "ref",
			columnType: "datetime",
			autoUpdatedAt: true
		},
		income_from_other_business: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		income_from_rent: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		income_from_agriculture: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		any_other_income: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		employment_id: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		existing_auto_loan: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		existing_personal_loan: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		existing_lap_loan: {
			type: "number",
			columnType: "DOUBLE",
			allowNull: true
		},
		auto_loan_bank_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		personal_loan_bank_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		lap_loan_bank_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		upi_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		deductions: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		income_loan_repayment: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			allowNull: true
		},
		income_range : {
			type: "string",
			columnType: "longtext",
			allowNull: true
		}
	}
};
