/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "lender_region_mapping",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "lender_region_mapping_id",
			isInteger: true
			// required: true
		},
		user_id: {
			// type: "number",
			// columnType: "int",
			// isInteger: true,
			// required: true,
			model: "usersrd",
			columnName: "user_id"
		},
		user_type: {
			type: "string",
			columnType: "enum",
			isIn: ["Bank", "Sales", "Revenue"],
			defaultsTo: "Bank"
		},
		region_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		createdon: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	}
};
