/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "loan_product_document_mapping",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "mapping_id",
			isInteger: true,
			required: true
		},
		loan_product_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		doctype_id: {
			model: "doctype"
		},
		businesstype_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		document_condition: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		initial_document_check: {
			type: "string",
			columnType: "enum",
			isIn: ["true", "false"]
		}
	}
};
