/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "loantype",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "typeId",
			isInteger: true,
			required: true
		},
		loanType: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		description: {
			type: "string",
			columnType: "text",
			required: true
		},
		display: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1"],
			defaultsTo: "0"
		},
		doc_detail: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		}
	}
};
