/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "loan_status_comments",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true
			//   required: true
		},
		loan_bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		user_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		user_type: {
			type: "string",
			columnType: "enum",
			isIn: ["Lender", "Borrower", "All", "Branch", "Credit", "Bank", "API", "Legal", "RCU", "BPO", "Technical", "Document"],
			defaultsTo: "All"
		},
		comment_text: {
			type: "string",
			columnType: "text",
			required: true
		},
		lender_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		created_time: {
			type: "string",
			columnType: "varchar",
			maxLength: 200
		},
		created_timestamp: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		assignee_id: {
			type: "number",
			columnType: "bigint",
			isInteger: true
		},
		lender_sub_status_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		comment_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45
		},
		doc_id: {
			type: "string",
			columnType: "text",
			allowNull: true
		}
	}
};
