/**
	Generated by sails-inverse-model
	Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "loan_bank_mapping",
	attributes: {
		id: {
			type: "number",
			columnType: "bigint",
			columnName: "loan_bank_mapping_id",
			isInteger: true,
			required: true
		},
		loan_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		business: {
			model: "businessrd",
			columnName: "business_id"
		},
		bank_id: {
			model: "bankmasterrd"
		},
		bank_emp_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_bank_status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_borrower_status: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		offer_amnt: {
			type: "number",
			columnType: "float"
		},
		offer_amnt_um: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores"]
		},
		interest_rate: {
			type: "number",
			columnType: "float"
		},
		term: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		emi: {
			type: "number",
			columnType: "float"
		},
		processing_fee: {
			type: "number",
			columnType: "float"
		},
		expected_time_to_disburse: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		offer_validity: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		remarks: {
			type: "string",
			columnType: "tinytext"
		},
		bank_assign_date: {
			type: "ref",
			columnType: "datetime"
		},
		lender_offer_date: {
			type: "ref",
			columnType: "datetime"
		},
		borrower_acceptence_date: {
			type: "ref",
			columnType: "datetime"
		},
		meeting_flag: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1", "2"],
			defaultsTo: "0"
		},
		notification_status: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "Yes"
		},
		lender_status: {
			columnName: "lender_status_id",
			model: "loanstatuswithlenderrd",
			required: true
		},
		upload_doc: {
			type: "string",
			columnType: "varchar",
			maxLength: 150
		},
		lender_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		create_at: {
			columnName: "ints",
			type: "ref",
			columnType: "datetime",
			required: true
		},
		updated_at: {
			columnName: "upts",
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		source: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			defaultsTo: "web"
		},
		status_history: {
			type: "string",
			columnType: "longtext"
		},
		loan_disbursement: {
			collection: "loandisbursementrd",
			via: "loan_bank_mapping_id"
		},
		lender_document: {
			collection: "lenderdocumentrd",
			via: "loan_bank_mapping"
		},
		reassign_nc_comments: {
			type: "string",
			columnType: "text"
		},
		pre_sanction_json: {
			type: "string",
			columnType: "json"
		},
		dscr: {
			type: "string",
			columnType: "varchar"
		},
		income: {
			type: "string",
			columnType: "varchar"
		},
		obligations: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		appraisal_inputs: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		applicant_coapplicant_summary: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		fee1: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		fee2: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		fee3: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		assigned_extended_ids: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		fee4: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		insurance_company1: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		insurance_company2: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		insurance_company3: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		insurance_company4: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		fee5: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		fee6: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		insurance_company5: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		insurance_company6: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		insurance_company7: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		fee7: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		insurance_company8: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		fee8: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		charge1: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		charge2: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		fee_deductible: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		approval_status: {
			type: "string",
			columnType: "longtext",
		},
		processing_fee_percent: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		sanction_additional_data: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		offer_additional_data: {
			type: "string",
			columnType: "json",
			allowNull: true
		}
	}
};
