/**
	Generated by sails-inverse-model
	Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "loanrequest",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "loanId",
			isInteger: true
		},
		loan_request_type: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		// business_id: {
		//     type: "number",
		//     columnType: "int",
		//     isIntege``````r: true
		// },
		business_id: {
			model: "business",
			required: true
		},
		loan_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 15
			// unique: true,
			// allowNull: true,
			// required: true
		},
		loan_amount: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		loan_amount_um: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores", "Thousand", "Millions"],
			allowNull: true
		},
		applied_tenure: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		assets_value: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		assets_value_um: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores", "Thousand", "Millions"],
			allowNull: true
		},
		annual_revenue: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		revenue_um: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores", "Thousand", "Millions"],
			allowNull: true
		},
		annual_op_expense: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		op_expense_um: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores", "Thousand", "Millions"],
			allowNull: true
		},
		cur_monthly_emi: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		// loan_asset_type_id: {
		//   type: 'number',
		//   columnType: 'int',
		//   isInteger: true,
		//   required: true
		// },
		loan_asset_type: {
			model: "Loanassettype",
			columnName: "loan_asset_type_id"
		},
		loan_usage_type: {
			model: "Loanusagetype",
			columnName: "loan_usage_type_id"
		},
		loan_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 50
		},
		loan_rating_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		loan_sub_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		remarks: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		remarks_val: {
			type: "string",
			columnType: "varchar",
			maxLength: 255
		},
		assigned_uw: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		assigned_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 11,
			allowNull: true
		},
		osv_doc: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "yes"
		},
		modified_on: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		RequestDate: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		loan_summary: {
			type: "string",
			columnType: "text",
			required: true
		},
		loan_product_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		notification: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		createdUserId: {
			model: "users"
		},
		white_label_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			defaultsTo: "1"
		},
		sales_id: {
			model: "users"
		},
		loan_originator: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_orginitaor: {
			model: "users"
		},
		doc_collector: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		unsecured_type: {
			model: "UnsecuredLoanAssetType"
		},
		remark_history: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		application_ref: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		document_upload: {
			type: "string",
			columnType: "enum",
			isIn: ["Done", "Pending"],
			allowNull: true
		},
		nc_status_history: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		loan_origin: {
			type: "string",
			columnType: "varchar",
			defaultsTo: "namaste_portal"
		},
		loan_document: {
			collection: "loandocument",
			via: "loan"
		},
		lender_document: {
			collection: "lenderdocument",
			via: "loan"
		},
		request_for_extract: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		notification_preapproved: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		notification_nc_biz_sales: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		b_city: {
			type: "string",
			columnType: "varchar"
		},
		case_priority: {
			type: "string",
			columnType: "varchar",
			defaultsTo: "Normal"
		},
		default_emails: {
			type: "json",
			columnType: "text"
		},
		default_zone: {
			type: "string",
			columnType: "varchar"
		},
		branch_id: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		loan_data: {
			type: "json",
			columnType: "text"
		},
		authentication_data: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		reportTat: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		connector_user_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		scheme_category_code: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		cusion_period: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		pre_emi: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			allowNull: true
		},
		credit_linked_insurance: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			allowNull: true
		},
		repayment_mode: {
			type: "string",
			columnType: "enum",
			isIn: ["Auto Recovery", "NACH"],
			allowNull: true
		},
		parent_product_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		assignment_additional: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		loanrequestcol : {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		}
	}
};
