/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "loan_products",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true,
			required: true
		},
		product: {
			type: "string",
			columnType: "varchar",
			maxLength: 200,
			required: true
		},
		payment_structure: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		security: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		loan_request_type: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		},
		loan_asset_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		loan_usage_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		parent_flag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		parent_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		created: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		create_json: {
			type: "json",
			columnType: "longtext"
		},
		edit_json: {
			type: "json",
			columnType: "longtext"
		},
		business_type_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		product_group_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		transaction_bucketing_type: {
			type: "string",
			columnType: "enum",
			isIn: ["full", "lean", "salaried", "us"]
		},
		application_json: {
			type: "json",
			columnType: "longtext"
		},
		dynamic_forms: {
			type: "json",
			columnType: "longtext"
		},
		additional_conditions: {
			type: "json",
			columnType: "longtext"
		},
		sanction_limit: {
			type: "json",
			columnType: "longtext"
		},
		conditions: {
			type: "string",
			columnType: "longtext"
		},
		terms_conditions: {
			type: "string",
			columnType: "longtext"
		},
		insurance_data: {
			type: "string",
			columnType: "longtext"
		}
	}
};
