/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "loan_product_details",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true,
			required: true
		},
		product_id: {
			type: "json",
			columnType: "json",
			required: true
		},
		white_label_id: {
			type: "number",
			columnType: "int",
			required: true
		},
		basic_details: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		product_details: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		color_theme_react: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		isActive: {
			type: "string",
			columnType: "enum",
			isIn: ["true", "false"],
			defaultsTo: "true"
		},
		edit_json: {
			type: "string",
			columnType: "text"
		},
		created_at: {
			type: "ref",
			columnType: "datetime",
			autoCreatedAt: true
		},
		updated_at: {
			type: "ref",
			columnType: "datetime",
			autoUpdatedAt: true
		},
		accounts_supported: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		cooling_period: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		loan_request_type: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		otp_configuration: {
			type: "json",
			columnType: "json"
		},
		terms_conditions_url: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		parent_id: {
			type: "string",
			columnType: "int",
			allowNull: true
		},
		sub_products: {
			type: "string",
			columnType: "enum",
			isIn: ["true", "false"]
		}
	}
};
