/**
Generated by sails-inverse-model
Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "loan_financials",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "fin_id",
			isInteger: true
			//   required: true
		},
		loan_id: {
			type: "number",
			columnType: "int",
			isInteger: true
			// required: true
		},
		business_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		fin_type: {
			type: "string",
			columnType: "enum",
			isIn: ["Bank Account", "Outstanding Loans", "Others", "Rental", "Credit Card", "OD", "CC", "Letter of Credit", "Personal Loan", "Home Loan", "Car Loan", "Two Wheeler Loan", "Education Loan", "Business Loan", "Payday Loan", "Mortgage Loan", "Gold Loan", "Agriculture Loan", "Consumer Durable Loan", "Medical Loan"]
			//   required: true,
		},
		bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true
			//   required: true,
		},
		loan_type: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		outstanding_balance: {
			type: "number",
			columnType: "float"
		},
		outstanding_balance_unit: {
			type: "string",
			columnType: "enum",
			isIn: ["Lakhs", "Crores"]
		},
		outstanding_start_date: {
			type: "string",
			columnType: "date"
		},
		outstanding_end_date: {
			type: "string",
			columnType: "date"
		},
		ints: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		account_type: {
			type: "string",
			columnType: "enum",
			isIn: ["OD", "CC", "Current", "Saving"],
			allowNull: true
		},
		account_number: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		account_limit: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		account_holder_name: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		bank_remarks: {
			model: "bankremarks",
			columnName: "bank_remark_id"
		},
		limit_type: {
			type: "string",
			columnType: "enum",
			isIn: ["Fixed", "Variable"],
			defaultsTo: "Fixed"
		},
		sanction_drawing_limit: {
			// type: "string",
			// columnType: "longtext"
			type: "json",
			columnType: "longtext"
		},
		IFSC: {
			type: "string",
			columnType: "varchar",
			allowNull: true,
			maxLength: 20
		},
		director_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"],
			defaultsTo: "active"
		},
		emi_details: {
			type: "string",
			columnType: "text"
		},
		source: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		loan_sub_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		remaining_loan_tenure: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		loan_acc_no: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		issuing_bank: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		credit_card_no: {
			type: "string",
			columnType: "varchar",
			maxLength: 40,
			allowNull: true
		},
		customer_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 40,
			allowNull: true
		},
		open_bank_account: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			defaultsTo: "NULL"
		},
		opened_in: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			allowNull: true
		},
		branch: {
			type: "string",
			columnType: "varchar",
			maxLength: 40,
			allowNull: true
		},
		bank_verification_status: {
			type: "json",
			columnType: "json",
		},
		bank_verification_flag: {
			type: "string",
			columnType: "enum",
			isIn: ['verified', 'failed', 'unverified', 'not-available', 'bad-gateway'],
			allowNull: true
		},
		enach_status: {
			type: "string",
			columnType: "enum",
			isIn: ['not-initiated', 'initiated', 'completed', 'cancelled', 'failed', 'expired'],
			allowNull: true
		},
		bank_track_data: {
			type: "json",
			columnType: "json"
		},
		enach_data: {
			type: "json",
			columnType: "json"
		},
		security_enach_status: {
			type: "string",
			columnType: "enum",
			isIn: ['not-initiated', 'initiated', 'completed', 'cancelled', 'failed', 'expired'],
			allowNull: true
		},
		security_enach_data: {
			type: "json",
			columnType: "json"
		},
		/*audit_trail: {
			type: "string",
			columnType: "json",
			allowNull: true
		},
		updated_by: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		data_update_flag: {
			type: "number",
			columnType: "int",
			allowNull: true
		}*/
	}
};
