/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "panno_response",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "panresponse_id",
			isInteger: true
			//   required: true
		},
		panno: {
			type: "string",
			columnType: "char",
			maxLength: 10,
			unique: true,
			required: true
		},
		response_code: {
			type: "string",
			columnType: "enum",
			isIn: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
		},
		pan_status: {
			type: "string",
			columnType: "enum",
			isIn: ["e", "f", "n"]
		},
		last_name: {
			type: "string",
			columnType: "char",
			maxLength: 75
		},
		first_name: {
			type: "string",
			columnType: "char",
			maxLength: 25
		},
		middle_name: {
			type: "string",
			columnType: "char",
			maxLength: 25
		},
		title: {
			type: "string",
			columnType: "char",
			maxLength: 6
		},
		pan_updated_date: {
			type: "string",
			columnType: "date"
		},
		filter1: {
			type: "string",
			columnType: "char",
			maxLength: 2
		},
		filter2: {
			type: "string",
			columnType: "char",
			maxLength: 10
		},
		filter3: {
			type: "string",
			columnType: "date"
		},
		pan_data_type: {
			type: "string",
			columnType: "set",
			required: true
		},
		unique_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255
		},
		response: {
			type: "string",
			columnType: "text"
		},
		ints: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		dt_created: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		remarks: {
			type: "string",
			columnType: "json",
			allowNull: true
		},
		verification_response: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
	}
};
