/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "physical_meetings_acceptance",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "meeting_id",
			isInteger: true
			//   required: true
		},
		loan_bank_mapping: {
			columnName: "loan_bank_mapping_id",
			model: "loanBankMapping",

			// type: 'number',
			// columnType: 'int',
			// isInteger: true,
			required: true
		},
		loan_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		borrower_user_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		bank_emp_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		meeting_type_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		remarks: {
			type: "string",
			columnType: "longtext"
		},
		meeting_timeslot: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		slot_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		meeting_location: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		ints: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		upts: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["initiated", "accepted", "declined"],
			defaultsTo: "Initiated"
		}
	}
};
