/**
  Generated by sails-inverse-model
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "region",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "region_id",
			isInteger: true
		},
		region_name: {
			type: "string",
			columnType: "varchar"
		},
		pincode_start_range: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		pincode_end_range: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"]
		}
	}
};
