/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "revenue_status",
	attributes: {
		id: {
			type: "number",
			columnType: "mediumint",
			columnName: "rev_id",
			required: true
		},
		status_caption: {
			type: "string",
			columnType: "text",
			required: true
		},
		controls: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		type: {
			type: "string",
			columnType: "enum",
			isIn: ["invoice", "revenue", "payment"],
			required: true
		},
		control_list: {
			type: "string",
			columnType: "text"
			// defaultsTo: {}
		},
		pre_condition: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		}
	},
	customToJSON: function () {
		if (this.control_list != "") {
			this.control_list = JSON.parse(this.control_list);
			return this;
		} else {
			this.control_list = {};
			return this;
		}
	}
};
