/**
  Generated by karthik s g
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "revenue_payment",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			isInteger: true
		},
		user: {
			model: "usersrd",
			columnName: "userid"
		},
		white_label_id: {
			type: "number",
			columnType: "int"
		},
		business: {
			model: "businessrd",
			columnName: "businessid"
		},
		loan: {
			model: "loanrequestrd",
			columnName: "loanid"
		},
		loan_bank_mapping: {
			model: "loanbankmappingrd",
			columnName: "loan_bank_mapping_id"
		},
		bank: {
			model: "bankmasterrd",
			columnName: "bank_id"
		},
		loan_product: {
			model: "loanproductsrd",
			columnName: "loan_product_id"
		},
		loan_disbursement: {
			model: "loandisbursementrd",
			columnName: "disbursementid"
		},
		status_caption: {
			type: "string",
			columnType: "text"
		},
		payment_status: {
			type: "number",
			columnType: "int"
		},
		payment: {
			model: "tblpaymentrd",
			columnName: "paymentId"
		}
	}
};
