/**
  Generated by karthik s g
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "revenue_payment",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			isInteger: true
		},
		user: {
			model: "users",
			columnName: "userid"
		},
		white_label_id: {
			type: "number",
			columnType: "int"
		},
		business: {
			model: "business",
			columnName: "businessid"
		},
		loan: {
			model: "loanrequest",
			columnName: "loanid"
		},
		loan_bank_mapping: {
			model: "loanbankmapping",
			columnName: "loan_bank_mapping_id"
		},
		bank: {
			model: "bankmaster",
			columnName: "bank_id"
		},
		loan_product: {
			model: "loanproducts",
			columnName: "loan_product_id"
		},
		loan_disbursement: {
			model: "loandisbursement",
			columnName: "disbursementid"
		},
		status_caption: {
			type: "string",
			columnType: "text"
		},
		payment_status: {
			type: "number",
			columnType: "int"
		},
		payment: {
			model: "tblpayment",
			columnName: "paymentId"
		}
	}
};
