/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "revenue_status_comments",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true
		},
		loan_bank_mapping_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 20
		},
		comments: {
			type: "string",
			columnType: "text",
			required: true
		},
		comment_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		type: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		notification: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		created_on: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		created_by: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		disbursement_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 12
		},
		invoice_summary_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		}
	}
};
