/**
 * SalesLoanData.js
 *
 * @description :: A model definition represents a database table/colllection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */
/**
  Generated by sails-inverse-model
  Date:Mon Mar 30 2020 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "sales_dashboard_loandump",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "disbursement_id",
			isInteger: true
		},
		category: {
			type: "string",
			columnType: "varchar",
			maxLength: 15
		},
		userid: {
			type: "number",
			columnType: "bigint",
			isInteger: true
		},
		loan_ref_id: {
			model: "Loanrequest",
			columnName: "loan_ref_id"
		},
		requestdate: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		llc_status: {
			type: "string",
			columnType: "varchar",
			maxLength: 13,
			allowNull: true
		},
		LenderStatus: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		BankName: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		volume_in_cr: {
			type: "number",
			columnType: "double",
			allowNull: true
		},
		product: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		LoanStatus: {
			type: "string",
			columnType: "varchar",
			maxLength: 19
		},
		sales_city: {
			type: "string",
			columnType: "varchar",
			maxLength: 150,
			allowNull: true
		},
		sales_state: {
			type: "string",
			columnType: "varchar",
			maxLength: 150,
			allowNull: true
		},
		sales: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		ChannelEMAIL: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		date: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		NCID: {
			type: "string",
			columnType: "varchar",
			maxLength: 36,
			allowNull: true
		},
		Channel_Name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		}
	}
};
