/**
    Generated by sails-inverse-model
    Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "tbl_payment_paid",
	attributes: {
		id: {
			type: "number",
			columnType: "bigint",
			isInteger: true,
			required: true
		},
		payments: {
			model: "tblPaymentrd",
			columnName: "payment_id",
			required: true
		},
		amount_paid: {
			type: "number",
			columnType: "double",
			required: true
		},
		amount_paid_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 25,
			required: true
		},
		txn_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		created_on: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		created_by: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		}
	}
};
