/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "tbl_payment",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			columnName: "paymentId",
			isInteger: true
		},
		disbursement_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		},
		loan_bank_mapping_id: {
			model: "loanbankmapping",
			required: true
		},
		disbursement_amount: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		payment_status: {
			model: "revenuestatus"
		},
		channel_payout_percentage: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		payable_amount: {
			type: "string",
			columnType: "varchar",
			maxLength: 90,
			required: true
		},
		subvention: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		net_amount: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		payable_tax: {
			type: "string",
			columnType: "varchar",
			maxLength: 89,
			required: true
		},
		payable_gst: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		net_payable: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		payout_percentage: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		payout_after: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		initiated_details: {
			type: "string",
			columnType: "varchar",
			maxLength: 1000,
			required: true
		},
		user_bank_id: {
			model: "userbank",
			columnName: "user_bank_id"
		},
		status: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			defaultsTo: "0"
		},
		notification: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		payment_created_by: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			allowNull: true
		},
		approved_by: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		created_on: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		approved_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 199,
			allowNull: true
		},
		updated_on: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		// partpaymentpaid_details: {
		//     type: "string",
		//     columnType: "longtext",
		//     required: true
		// },
		payment_paid: {
			collection: "tblpaymentpaid",
			via: "payments"
		}
	}
};
