/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "user_bank",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true
		},
		userid: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		bank_ref_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		bank_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		acc_holder_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		bank_balance: {
			type: "number",
			columnType: "double",
			defaultsTo: 0
		},
		balance_updated_date_time: {
			type: "string",
			columnType: "varchar",
			maxLength: 20
		},
		acc_no: {
			type: "string",
			columnType: "varchar",
			maxLength: 20,
			required: true
		},
		ifsc: {
			type: "string",
			columnType: "varchar",
			maxLength: 20,
			required: true
		},
		acc_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 40,
			required: true
		},
		yodlee_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 20
		},
		status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		bank_limit_npci: {
			type: "number",
			columnType: "double",
			defaultsTo: 0
		},
		bank_balance_minum: {
			type: "number",
			columnType: "decimal",
			defaultsTo: 0
		},
		npci_status: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "NO"
		},
		npci_code: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			allowNull: true
		},
		npci_date: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		npci_request_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		created_date: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		updated_date: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		preference: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		row_id_ref: {
			type: "string",
			columnType: "varchar",
			maxLength: 100
		},
		madate_status: {
			type: "string",
			columnType: "enum",
			isIn: ["no", "yes"],
			defaultsTo: "no"
		},
		mandate_received_form: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		signed_mandate: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		mandate_ref: {
			type: "string",
			columnType: "text"
		},
		ocr_file_path: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		mandate_file_name: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		providerAccountId: {
			type: "string",
			columnType: "varchar",
			maxLength: 120,
			allowNull: true
		},
		mandate_sent_status: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		is_ca_account: {
			type: "number",
			columnType: "tinyint",
			isInteger: true,
			defaultsTo: 0
		},
		document_url: {
			type: "string",
			columnType: "text",
			allowNull: true
		}
	}
};
