/**
  Generated by sails-inverse-model
  Date:Tue Jan 19 2021 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "user_document",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "doc_id",
			isInteger: true
		},
		user_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		doc_type_id: {
			type: "number",
			columnType: "int",
			isInteger: true
		},
		doc_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 200
		},
		uploaded_doc_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "deleted", "inactive"],
			required: true
		},
		white_label_id: {
			type: "number",
			columnType: "int"
		},
		no_of_pages: {
			type: "string",
			columnType: "varchar",
			maxLength: 256,
			allowNull: true
		},
		bank_tags: {
			type: "number",
			columnType: "int",
			columnName: "bizBank_tags",
			allowNull: true
		},
		origin: {
			type: "string",
			columnType: "varchar"
		},
		created: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		updated_date: {
			type: "ref",
			columnType: "datetime",
			defaultsTo: "CURRENT_TIMESTAMP"
		}
	}
};
