/**
 * ViewLoan.js
 *
 * @description :: A model definition represents a database table/colllection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */

/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_viewloan",
	tableName: "view_loan",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "loanId",
			isInteger: true
		},
		loan_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 15,
			allowNull: true
		},
		loan_asset_type: {
			model: "Loanassettyperd",
			columnName: "loan_asset_type_id"
		},
		loan_usage_type: {
			columnName: "loan_usage_type_id",
			model: "loanusagetyperd"
		},
		loan_type: {
			columnName: "loan_type_id",
			model: "loantyperd"
		},

		loan_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1,
			allowNull: true
		},
		loan_sub_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		modified_on: {
			type: "ref",
			columnType: "timestamp"
		},
		loan_products: {
			columnName: "loan_product_id",
			model: "LoanProductsrd"
		},
		white_label_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			defaultsTo: "1"
		},
		loan_bank_mapping: {
			columnName: "loan_bank_mapping_id",
			model: "loanbankmappingrd"
		},
		loan: {
			model: "loanrequestrd",
			columnName: "loan_id"
		},
		bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		bank_emp_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		loan_bank_status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		loan_borrower_status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		upts: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "0000-00-00 00:00:00"
		},
		lender_status: {
			columnName: "lender_status_id",
			model: "loanstatuswithlenderrd"
		},
		business: {
			columnName: "businessid",
			model: "businessrd"
		},
		businessname: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		users: {
			columnName: "userid",
			model: "usersrd"
		},
		business_email: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		sales_id: {
			columnName: "sales_id",
			model: "usersrd"
		},
		doc_upload_status: {
			type: "string",
			columnType: "enum",
			columnName: "document_upload",
			isIn: ["Done", "Pending"],
			defaultsTo: "Pending"
		},
		createdUserId: {
			type: "string",
			columnType: "varchar"
		},
		region_id: {
			type: "number",
			columnType: "bigint",
			isInteger: true,
			allowNull: true
		},
		city: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		doc_count: {
			type: "number",
			columnType: "bigint",
			allowNull: true
		},
		assigned_extended_ids: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		meeting_flag: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1", "2"],
			defaultsTo: "0"
		},
		state: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		branch_id: {
			type: "number",
			columnType: "int",
			allowNull: true
		},
		zone_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			allowNull: true
		},
		/*channel_type: {
			type: "string",
			columnType: "enum",
			isIn: ['Normal', 'Green'],
			defaultsTo: 'Normal'
		}*/
	},
	customToJSON: function () {
		// Return a shallow copy of this record with the password and ssn removed.
		return _.omit(this, [
			"loan_ref_id",
			"businessname",
			"business_email",
			"loan_status_id",
			"loan_sub_status_id",
			"loan_bank_status",
			"loan_borrower_status",
			"bank_id",
			"bank_emp_id"
		]);
	}
};
