/**
 * ViewLoanListingData.js
 *
 * @description :: A model definition represents a database table/colllection.
 * @docs        :: https://sailsjs.com/docs/concepts/models-and-orm/models
 */

/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "view_loan_listing_data",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "loanId",
			isInteger: true
		},
		loan_ref_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 15,
			allowNull: true
		},
		loan_amount: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		gstin: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		loan_amount_um: {
			type: "string",
			columnType: "enum",
			isIn: ["lakhs", "crores"]
		},
		applied_tenure: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		loan_request_type: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		assets_value: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		assets_value_um: {
			type: "string",
			columnType: "enum",
			isIn: ["lakhs", "crores"]
		},
		annual_revenue: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		revenue_um: {
			type: "string",
			columnType: "enum",
			isIn: ["lakhs", "crores"]
		},
		annual_op_expense: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		op_expense_um: {
			type: "string",
			columnType: "enum",
			isIn: ["lakhs", "crores"]
		},
		cur_monthly_emi: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		loan_asset_type: {
			model: "Loanassettyperd",
			columnName: "loan_asset_type_id"
		},
		loan_usage_type: {
			columnName: "loan_usage_type_id",
			model: "loanusagetyperd"
		},
		loan_type_id: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		loan_rating: {
			columnName: "loan_rating_id",
			model: "LoanRatingrd"
		},
		loan_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1,
			allowNull: true
		},
		loan_sub_status_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		assigned_uw: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		assigned_date: {
			type: "string",
			columnType: "varchar",
			maxLength: 11,
			allowNull: true
		},
		loan_summary: {
			type: "string",
			columnType: "text",
			required: true
		},
		modified_on: {
			type: "ref",
			columnType: "timestamp"
		},
		RequestDate: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		loan_products: {
			columnName: "loan_product_id",
			model: "LoanProductsrd"
		},
		white_label_id: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			defaultsTo: "1"
		},
		loan_bank_mapping: {
			columnName: "loan_bank_mapping_id",
			model: "loanbankmappingrd"
		},
		loan: {
			model: "loanrequestrd",
			columnName: "loan_idrd"
		},
		bank_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		bank_emp_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		loan_bank_status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		loan_borrower_status: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		offer_amnt: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		offer_amnt_um: {
			type: "string",
			columnType: "enum",
			isIn: ["lakhs", "crores"]
		},
		interest_rate: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		term: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		emi: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		processing_fee: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		expected_time_to_disburse: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		offer_validity: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		remarks: {
			type: "string",
			columnType: "tinytext",
			allowNull: true
		},
		bank_assign_date: {
			type: "ref",
			columnType: "datetime"
		},
		lender_offer_date: {
			type: "ref",
			columnType: "datetime"
		},
		borrower_acceptence_date: {
			type: "ref",
			columnType: "datetime"
		},
		meeting_flag: {
			type: "string",
			columnType: "enum",
			isIn: ["0", "1", "2"],
			defaultsTo: "0"
		},
		upload_doc: {
			type: "string",
			columnType: "varchar",
			maxLength: 150,
			allowNull: true
		},
		ints: {
			type: "ref",
			columnType: "datetime",
			required: true
		},
		upts: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "0000-00-00 00:00:00"
		},
		lender_status: {
			columnName: "lender_status_id",
			model: "loanstatuswithlenderrd"
		},
		business: {
			columnName: "businessid",
			model: "businessrd"
		},
		businessname: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		business_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		users: {
			columnName: "userid",
			model: "usersrd"
		},
		first_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			allowNull: true
		},
		last_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			allowNull: true
		},
		business_email: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		contactno: {
			type: "string",
			columnType: "varchar",
			maxLength: 15,
			allowNull: true
		},
		businesstype: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		businessindustry: {
			model: "Businessindustryrd"
		},
		businessstartdate: {
			type: "string",
			columnType: "varchar",
			maxLength: 30,
			required: true
		},
		businesspancardnumber: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			required: true
		},
		corporateid: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			allowNull: true
		},
		percentage_business_supplier: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		percentage_business: {
			type: "number",
			columnType: "float",
			allowNull: true
		},
		empcount: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		noofdirectors: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 1
		},
		about_business: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		status: {
			type: "string",
			columnType: "enum",
			isIn: ["active", "inactive", "deleted"],
			defaultsTo: "active"
		},
		us_email: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		us_usertype: {
			type: "string",
			columnType: "varchar",
			maxLength: 300,
			defaultsTo: "Borrower"
		},
		us_assigned_sales_user: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		us_parent_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0,
			allowNull: true
		},
		us_lender_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		bank: {
			columnName: "bankid",
			model: "bankmasterrd"
		},
		bankname: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		isLender: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"],
			defaultsTo: "No"
		},
		type: {
			type: "string",
			columnType: "enum",
			isIn: ["bank", "nbfc"],
			defaultsTo: "Bank"
		},
		category: {
			type: "string",
			columnType: "enum",
			isIn: ["nbfc", "regional bank", "international bank", "national private bank", "national public bank"],
			defaultsTo: "National Public Bank"
		},
		loan_orginator: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		sales_id: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		lbmupts: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "0000-00-00 00:00:00"
		},
		doc_collector: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		},
		unsecured_type: {
			type: "number",
			columnType: "int",
			isInteger: true,
			allowNull: true
		}
	}
};
