/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_read",
	tableName: "white_label_permission",
	attributes: {
		name_tag: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			required: true
		},
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true,
			required: true
		},
		permission: {
			type: "json",
			columnType: "longtext",
			required: true
		},
		white_label: {
			columnName: "white_label_id",
			model: "whitelabelsolutionrd"
		},
		alias_user_type : {
			type: "string",
			columnType: "varchar",
			maxLength: 150,
			allowNull: true

		}
	}
};
