/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit_write",
	tableName: "white_label_solution",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "int",
			isInteger: true,
			required: true
		},
		name: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		site_url: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		s3_name: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		s3_region: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			defaultsTo: "ap-southeast-1"
		},
		associated_bank: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		logo: {
			type: "string",
			columnType: "text",
			required: true
		},
		available_user_type: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		created_date_time: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		status: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		password_rule: {
			type: "string",
			columnType: "enum",
			isIn: ["no", "yes"],
			required: true
		},
		slug: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		css_path: {
			type: "string",
			columnType: "varchar",
			maxLength: 100,
			defaultsTo: "http://dcysiw431a2n2.cloudfront.net/default-green.css"
		},
		doctype_to_extract: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		adharVerifyFlag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		passportVerifyFlag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		voterIdFlag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		drivingLisenceFlag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		default_mailer: {
			type: "string",
			columnType: "text",
			required: true
		},
		analysis: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		analysis_doctype: {
			type: "string",
			columnType: "text",
			maxLength: 45,
			allowNull: true
		},
		uw_qc: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0,
			allowNull: true
		},
		date_format_region: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		date_for_monthly_filtration: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		statement_accuracy: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		csersaiflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		CERSAI_USER: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		},
		CERSAI_PASS: {
			type: "string",
			columnType: "varchar",
			maxLength: 50,
			required: true
		},
		updated_time_up: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		legalcheckflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		googleflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		truecallerflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		gstflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		rocflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		associatedcompflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		kycflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		cibilflag: {
			type: "number",
			columnType: "int",
			isInteger: true,
			defaultsTo: 0
		},
		searchtype: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		itr_flag: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			defaultsTo: "0",
			allowNull: true
		},
		itr_file_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 45,
			allowNull: true
		},
		solution_type: {
			type: "string",
			columnType: "enum",
			isIn: ["los", "banking", "financial", "finbank"],
			defaultsTo: "LOS"
		},
		bankuser_assignment_type: {
			type: "string",
			columnType: "enum",
			isIn: ["sales", "credit", "cpa"],
			defaultsTo: "Sales"
		},
		loan_product_type: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		assignment_type: {
			type: "json",
			columnType: "text",
			required: true
		},
		payment_extract_email: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		color_theme_react: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		encryption_flag: {
			type: "string",
			columnType: "enum",
			isIn: ["yes", "no"]
		},
		country: {
			type: "string",
			columnType: "varchar",
			defaultsTo: "India",
			maxLength: 50
		},
		password_history_count: {
			type: "number",
			columnType: "int"
		},
		password_reuse_policy: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		transaction_bucketing_type: {
			type: "string",
			columnType: "enum",
			isIn: ["full", "lean", "specific"]
		},
		ref_bank_id: {
			type: "number",
			columnType: "int"
		},
		isApplicationformenabled: {
			type: "number",
			columnType: "tinyint",
			defaultsTo: 0,
			allowNull: true
		},
		document_mapping: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		geo_tagging: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		user_profile_access: {
			type: "string",
			columnType: "longtext",
			allowNull: true
		},
		sanction_type: {
			type: "string",
			columnType: "enum",
			isIn: ["Final Sanction", "In-Principle Sanction"],
			defaultsTo: "Final Sanction"
		},
		mandatory_field: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		eod_process: {
			type: "string",
			columnType: "text",
			allowNull: true
		},
		product_line: {
			type: "string",
			columnType: "text",
			allowNull: true
		}
		// otherdocumentMapping: {
		//     type: "string",
		//     columnType: "text"
		// }
	},
	customToJSON: function () {
		// Return a shallow copy of this record with the password and ssn removed.
		return _.omit(this, [
			"available_user_type",
			"doctype_to_extract",
			"default_mailer",
			"CERSAI_USER",
			"CERSAI_PASS"
		]);
	}
};
