export const initialFormState = {
	employment_category: 'Salaried',
	organization_type: 'Private Limited',
	organization_type_salaried: 'Partnership',
	company_name: 'NC',
	current_designation: 'SDE',
	years_in_company: '2015',
	total_experience: '10',
	office_phone: '9825252552',
	office_email: 'nc@gmail.com',

	address1: 'Add Line 1',
	address2: 'Add Line 2',
	landmark: 'Landmark',
	address3: 'Landmark',
	pin_code: '560078',
	city: 'Bangalore',
	state: 'Karnataka',

	gross_income: '100000',
	net_monthly_income: '100000',
	income_from_other_business: '100000',
	income_from_rent: '100000',
	income_from_agriculture: '100000',
	any_other_income: '100000',
};
