export const initialFormState = {
	collateral_type: 'Apartment',
	current_market_value: '100000',
	collateral_sub_type: 'Resale',
	property_type: 'Factory',
	nature_of_property: 'Apartment',
	total_area: '1000',
	construction_area: '1000',
	age: '2023-01',
	property_purpose: 'Vacant',
	property_ownership: 'Lease Hold',
	property_amount: '1000000',
	owner_type: 'Previous',
	ownership_status: 'Single',
	owner_name: 'Tensa',
	ownership_from: '2023-01-01',
	percent_share: '50',

	address1: 'Add Line 1',
	address2: 'Add Line 2',
	landmark: 'Landmark',
	address3: 'Landmark',
	pin_code: '560078',
	pinCode: '560078',
	city: 'Bangalore',
	state: 'Karnataka',

	nature_of_ownership: 'Inherited',
	property_occupant: 'Mortgagor',
};
