/**
  Generated by sails-inverse-model
  Date:Fri Feb 22 2019 15:11:02 GMT+0530 (India Standard Time)
*/

module.exports = {
	datastore: "mysql_namastecredit",
	tableName: "businessaddress",
	attributes: {
		id: {
			type: "number",
			autoIncrement: true,
			columnType: "bigint",
			columnName: "baid",
			isInteger: true
		},
		bid: {
			model: "business",
			required: true
		},
		aid: {
			type: "number",
			columnType: "int",
			isInteger: true,
			required: true
		},
		line1: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		line2: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		line3: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		line4: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			allowNull: true
		},
		locality: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		city: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		state: {
			type: "string",
			columnType: "varchar",
			maxLength: 255,
			required: true
		},
		pincode: {
			type: "string",
			columnType: "varchar",
			maxLength: 10,
			required: true
		},
		address_status: {
			type: "string",
			columnType: "enum",
			isIn: ["mortgaged", "owned", "leased", "rented"]
		},
		residential_stability: {
			type: "string",
			columnType: "varchar",
			maxLength: 255
		},
		ints: {
			type: "ref",
			columnType: "timestamp",
			defaultsTo: "CURRENT_TIMESTAMP"
		},
		residential_type: {
			type: "string",
			columnType: "enum",
			isIn: ["owned", "rented", "Owned", "Rented", "Family", "Renter", "Employer", "Others"]
		},
		address_type: {
			type: "string",
			columnType: "varchar",
			allowNull: true
		},
		preferred_mailing_address: {
			type: "string",
			columnType: "enum",
			isIn: ["Yes", "No"],
			allowNull: true
		}
	}
};
