version: "1"

services:
    mysql:
    image: mysql
    build: ./
    environment:
        - MYSQL_HOST=ncndevelop-migrated-cluster.cluster-chaqiqb07wh0.ap-southeast-1.rds.amazonaws.com
        - MYSQL_DATABASE=namastecredit
        - MYSQL_USER=webappuser
        - MYSQL_PASSWORD=Bangalore2018@

    sails:
        build:
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - mysql
        environment:
            - MYSQL_USER=webappuser
            - USE_DOCKER=yes
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        links:
            - mysql
