export const initialFormState = {
	existing_customer: 'Yes',
	pan_number: 'ABCDE2222F',
	income_type: '7',
	first_name: 'Tensa',
	last_name: 'Zangetsu',
	dob: '1994-11-05',
	gender: 'Male',
	email: 'varunbhai.miyani@namastecredit.com',
	mobile_no: '8892538145',
	marital_status: 'Married',
	spouse_name: 'Tensa',
	residence_status: 'Resident',
	country_residence: 'India',
	father_name: 'Father Name',
	mother_name: 'Mother Name',
	upi_id: '1111111',
};
